apiVersion: tensorstack.dev/v1beta1
kind: Notebook
metadata:
  name: ""
spec:
  type: jupyter
  template:
    spec:
      containers:
        - name: notebook
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_PTRACE"]
          ## @param spec.template.spec.containers[0].image The image used for the notebook container.
          image: registry.cn-hangzhou.aliyuncs.com/t9k/jupyterlab-torch-2.1.0:240708-dcu
          volumeMounts:
            - name: workingdir
              mountPath: /t9k/mnt
            - name: hyhal
              mountPath: /opt/hyhal
              readOnly: true
            - name: dev-kfd
              mountPath: /dev/kfd
              readOnly: true
            - name: dev-dri
              mountPath: /dev/dri
              readOnly: true
          ## @param spec.template.spec.containers[0].resources.limits.cpu The maximum number of CPU the notebook can use.
          ## @param spec.template.spec.containers[0].resources.limits.memory The maximum number of CPU the notebook can use.
          resources:
            limits:
              cpu: "4"
              memory: 8Gi
              hygon.com/dcu: 1
      volumes:
        - name: workingdir
          persistentVolumeClaim:
            ## @param spec.template.spec.volumes[0].persistentVolumeClaim.claimName Mount a pvc as notebook working directory.
            claimName: ""
        - name: hyhal
          hostPath:
            path: /opt/hyhal
        - name: dev-kfd
          hostPath:
            path: /dev/kfd
        - name: dev-dri
          hostPath:
            path: /dev/dri
