apiVersion: tensorstack.dev/v1beta1
kind: Explorer
metadata:
  name: ""
spec:
  ## @param spec.storageName Select a pvc as CodeServer workspace.
  storageName: ""
  storageType: pvc
  type: CodeServer
