apiVersion: app.tensorstack.dev/v1beta1
kind: Template
metadata:
  name: codeserver
  displayName: "Code Server"
  categories: 
  - IDE
  description: "Code Server 是一个基于浏览器的 VSCode 环境。"
  icon: "file://$APP_DIR/icon.svg"
template:
  helm: 
    repo: "oci://docker.io/t9kpublic"
    chart: "codeserver"
    versions:
    - version: 0.2.1
      config: "file://$APP_DIR/configs/v0_2_1.yaml"
      urls: 
      - name: "codeserver"
        url: "/t9k/build-console/projects/{{ .Release.Namespace }}/explorers/{{ .Release.Name }}/codeserver/"
      readinessProbe:
        resources:
        - group: tensorstack.dev
          version: v1beta1
          resource: explorers
          name: "{{ .Release.Name }}"
          message: "{{- range .status.conditions }}{{- if eq .type \"Ready\" }}{{- .message }}{{- end }}{{- end }}"
          currentStatus: "{{- range .status.conditions }}{{- if eq .type \"Ready\" }}{{- .status }}{{- end }}{{- end }}"
          desiredStatus: "True"
      dependencies:
        crds:
        - group: tensorstack.dev
          version: v1beta1
          resource: explorers
