apiVersion: v2
name: dify
description: A Helm chart for Dify
type: application
version: 0.3.8
appVersion: 0.11.2
dependencies:
- condition: redis.embedded
  name: redis
  repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
  version: ~19.1.1
- condition: postgresql.embedded
  name: postgresql
  repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
  version: ~15.2.5
- condition: minio.embedded
  name: minio
  repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
  version: ~14.1.7
- condition: qdrant.embedded
  name: qdrant
  version: ~1.12.4
  repository: https://qdrant.github.io/qdrant-helm
maintainers:
- name: douban
home: https://github.com/langgenius/dify
