apiVersion: v2
appVersion: 1.3.1.post1
dependencies:
- condition: redis.embedded
  name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: ~19.1.1
- condition: postgresql.embedded
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: ~15.2.5
- condition: minio.embedded
  name: minio
  repository: oci://registry-1.docker.io/bitnamicharts
  version: ~14.1.7
description: A Helm chart for Dify
home: https://github.com/langgenius/dify
maintainers:
- name: douban & t9k
name: dify
type: application
version: 0.7.0
