{{- if not .Values.persistence.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "stable-diffusion-webui-aki.fullname" . }}
  labels:
  {{- include "stable-diffusion-webui-aki.labels" . | nindent 4 }}
spec:
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass -}}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  accessModes:
  {{- toYaml .Values.persistence.accessModes | nindent 4 }}
{{- end }}
