## @param image.registry JupyterLab image registry
## @param image.repository JupyterLab image repository
## @param image.tag JupyterLab image tag
## @param image.pullPolicy JupyterLab image pull policy
##
image:
  registry: "$(T9K_APP_IMAGE_REGISTRY)"
  repository: "$(T9K_APP_IMAGE_NAMESPACE)/jupyterlab-torch-2.5.0"
  tag: "20241031"
  pullPolicy: IfNotPresent

## @param pvc Mount a PVC as JupyterLab workspace
pvc: ""

## @param resources.limits.cpu CPU limit for JupyterLab container
## @param resources.limits.memory Memory limit for JupyterLab container
## @param resources.limits."nvidia.com/gpu" NVIDIA GPU limit for JupyterLab container
resources:
  limits:
    cpu: 16
    memory: 32Gi
    nvidia.com/gpu: 1

## @param ssh.enabled Set true to start a SSH Service for JupyterLab
## @param ssh.authorizedKeys A list of names of v1.Secret containing SSH public keys authorized for access to this SSH service
## @param ssh.serviceType Type for the SSH service (`ClusterIP` or `NodePort`)
#
# ssh:
#   enabled: true
#   authorizedKeys:
#   - "secret-name"
#   serviceType: ClusterIP
#
ssh:
  enabled: false
  authorizedKeys: []
  serviceType: ClusterIP
