apiVersion: app.tensorstack.dev/v1beta1
kind: Template
metadata:
  name: llama-board
  displayName: "Llama Board"
  categories: ["AI"]
  description: "Llama Board 是 LLaMA-Factory 项目的 web UI，用于（增量）预训练、指令微调和评估开源 LLM。"
  icon: "file://$APP_DIR/icon.png"
template:
  helm:
    repo: "oci://docker.io/t9kpublic"
    # repo: "https://t9k.github.io/apps/"
    chart: "llama-board"
    versions:
    - version: 0.1.0
      urls: []
      # - name: UI
      #   url: /apps/{{ .Release.Namespace }}/fish-speech/{{ .Release.Name }}/
      readinessProbe:
        resources:
        - group: apps
          version: v1
          resource: deployments
          name: "{{ .Release.Name }}"
          currentStatus: "{{- range .status.conditions }}{{- if eq .type \"Available\" }}{{- .status }}{{- end }}{{- end }}"
          desiredStatus: "True"
      dependencies: {}
