## @param image.registry ComfyUI image registry
## @param image.repository ComfyUI image repository
## @param image.tag ComfyUI image tag
## @param image.pullPolicy ComfyUI image pull policy
##
image:
  registry: "$(T9K_APP_IMAGE_REGISTRY)"
  repository: "$(T9K_APP_IMAGE_NAMESPACE)/comfyui"
  tag: "v0.2.3"
  pullPolicy: IfNotPresent

## @param resources.limits.cpu CPU limit for ComfyUI container
## @param resources.limits.memory Memory limit for ComfyUI container
## @param resources.limits."nvidia.com/gpu" NVIDIA GPU limit for ComfyUI container
##
resources:
  limits:
    cpu: 4
    memory: 64Gi
    nvidia.com/gpu: 1

## @param persistence.size Size of the PVC
## @param persistence.storageClass Storage class for the PVC
## @param persistence.accessModes Access modes for the PVC
## @param persistence.existingClaim Name of an existing PVC to use
##
persistence:
  size: 64Gi
  storageClass: ""
  accessModes:
  - ReadWriteOnce
  existingClaim: ""

## @param env Array of extra environment variables
##
env: []
  # # HTTP 和 HTTPS 代理
  # - name: http_proxy
  #   value: ""
  # - name: https_proxy
  #   value: ""
