image:
  server:
    registry: "$(T9K_APP_IMAGE_REGISTRY)"
    repository: "$(T9K_APP_IMAGE_NAMESPACE)/vllm-openai"
    tag: "v0.6.3"
    pullPolicy: IfNotPresent

  initializer:
    registry: "$(T9K_APP_IMAGE_REGISTRY)"
    repository: "$(T9K_APP_IMAGE_NAMESPACE)/kubectl"
    tag: "1.27"
    pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 4
    memory: 64Gi

model:
  deployName: ""

  volume:
    storageClass: ""
    size: 32Gi
    accessModes:
      - ReadWriteOnce
    existingClaim: ""
    subPath: ""

  source: ""
  huggingface:
    id: ""
    files: ""
    existingSecret: ""
  git:
    url: ""
    ref: ""
    existingSecret: ""
  s3:
    url: ""
    existingSecret: ""

autoScaling:
  minReplicas: ""
  maxReplicas: ""
  annotations: {}

app:
  extraArgs: []

env: []
