apiVersion: app.tensorstack.dev/v1beta1
kind: Template
metadata:
  name: rstudio
  displayName: RStudio
  categories: 
  - IDE
  description: "RStudio 集成开发环境（IDE），旨在帮助你提高 R 和 Python 的工作效率。"
  icon: "file://$APP_DIR/icon.svg"
template:
  crd:
    group: tensorstack.dev
    resource: notebooks
    versions:
    - version: v1beta1
      config: "file://$APP_DIR/config.yaml"
      readme: "file://$APP_DIR/README.md"
      note: "file://$APP_DIR/NOTE.txt"
      urls: 
      - name: "rstudio"
        url: "/t9k/notebooks/projects/{{ .metadata.namespace }}/name/{{ .metadata.name }}/"
      readinessProbe:
        resources:
        - group: tensorstack.dev
          version: v1beta1
          resource: notebooks
          name: "{{ .metadata.name }}"
          currentStatus: "{{- range .status.conditions }}{{- if eq .type \"Ready\" }}{{- .status }}{{- end }}{{- end }}"
          desiredStatus: "True"
      dependencies:
        crds:
        - group: tensorstack.dev
          version: v1beta1
          resource: notebooks
