apiVersion: app.tensorstack.dev/v1beta1
kind: Template
metadata:
  name: filebrowser
  displayName: "FileBrowser"
  categories: 
  - Tool
  description: "FileBrowser 在指定目录中提供了一个文件管理界面，可用于上传、删除、预览、重命名和编辑您的文件。"
  icon: "file://$APP_DIR/filebrowser/icon.svg"
template:
  crd:
    group: tensorstack.dev
    resource: explorers
    versions:
    - version: v1beta1
      config: "file://$APP_DIR/filebrowser/config.yaml"
      readme: "file://$APP_DIR/filebrowser/README.md"
      note: "file://$APP_DIR/filebrowser/NOTE.txt"
      urls: 
      - name: "filebrowser"
        url: "/t9k/build-console/projects/{{ .metadata.namespace }}/explorers/{{ .metadata.name }}/filebrowser/"
      readinessProbe:
        resources:
        - group: tensorstack.dev
          version: v1beta1
          resource: explorers
          name: "{{ .metadata.name }}"
          currentStatus: "{{- range .status.conditions }}{{- if eq .type \"Ready\" }}{{- .status }}{{- end }}{{- end }}"
          desiredStatus: "True"
      dependencies:
        crds:
        - group: tensorstack.dev
          version: v1beta1
          resource: explorers

---

apiVersion: app.tensorstack.dev/v1beta1
kind: Template
metadata:
  name: codeserver
  displayName: "CodeServer"
  categories: 
  - Tool
  description: "CodeServer 是一个可以通过浏览器访问的 VSCode。"
  icon: "file://$APP_DIR/codeserver/icon.svg"
template:
  crd:
    group: tensorstack.dev
    resource: explorers
    versions:
    - version: v1beta1
      config: "file://$APP_DIR/codeserver/config.yaml"
      readme: "file://$APP_DIR/codeserver/README.md"
      note: "file://$APP_DIR/codeserver/NOTE.txt"
      urls: 
      - name: "codeserver"
        url: "/t9k/build-console/projects/{{ .metadata.namespace }}/explorers/{{ .metadata.name }}/codeserver/"
      readinessProbe:
        resources:
        - group: tensorstack.dev
          version: v1beta1
          resource: explorers
          name: "{{ .metadata.name }}"
          currentStatus: "{{- range .status.conditions }}{{- if eq .type \"Ready\" }}{{- .status }}{{- end }}{{- end }}"
          desiredStatus: "True"
      dependencies:
        crds:
        - group: tensorstack.dev
          version: v1beta1
          resource: explorers
