apiVersion: app.tensorstack.dev/v1beta1
kind: Template
metadata:
  name: vllm
  displayName: vLLM
  categories: ["AI"]
  description: "vLLM 是一个用于大语言模型的高吞吐量和内存高效的推理和服务引擎。"
  icon: "file://$APP_DIR/icon.png"
template:
  helm:
    repo: oci://registry.dockermirror.com/t9kpublic
    # repo: oci://registry.dockermirror.com/t9kpublic
    chart: "vllm"
    versions:
    - version: 0.1.7
      urls: []
      readinessProbe:
        resources:
        - group: tensorstack.dev
          version: v1beta1
          resource: simplemlservices
          name: "{{ .Release.Name }}"
          currentStatus: "{{- range .status.conditions }}{{- if eq .type \"Ready\" }}{{- .status }}{{- end }}{{- end }}"
          desiredStatus: "True"
      dependencies: {}
