## @param image.registry DB-GPT image registry
## @param image.repository DB-GPT image repository
## @param image.tag DB-GPT image tag
## @param image.pullPolicy DB-GPT image pull policy
##
image:
  registry: "$(T9K_APP_IMAGE_REGISTRY)"
  repository: "$(T9K_APP_IMAGE_NAMESPACE)/dbgpt-allinone"
  tag: "v0.6.2"
  pullPolicy: IfNotPresent

## @param dotenv.enabled Enable/disable environment variable configuration
## @param dotenv.data Environment variables configuration
##
dotenv:
  enabled: true
  # 应用的配置，请参阅 https://github.com/eosphoros-ai/DB-GPT/blob/main/.env.template
  #
  # 聊天模型配置示例
  #   LLM_MODEL=proxyllm
  #   PROXY_SERVER_URL=http://app-vllm-1264b243.dev-xyx.nc201.ksvc.tensorstack.net/v1/chat/completions
  #   PROXY_API_KEY=any
  #   PROXYLLM_BACKEND=qwen2.5:7b
  #
  # 嵌入模型配置示例
  #   EMBEDDING_MODEL=proxy_http_openapi
  #   proxy_http_openapi_proxy_server_url=http://app-vllm-4b9ab43.dev-xyx.nc201.ksvc.tensorstack.net/v1/embeddings
  #   proxy_http_openapi_proxy_api_key=any
  #   proxy_http_openapi_proxy_backend=e5-mistral-7b-instruct
  #
  data: |-
    LLM_MODEL=proxyllm
    PROXY_SERVER_URL=
    PROXY_API_KEY=
    PROXYLLM_BACKEND=

    EMBEDDING_MODEL=proxy_http_openapi
    proxy_http_openapi_proxy_server_url=
    proxy_http_openapi_proxy_api_key=
    proxy_http_openapi_proxy_backend=

    LOCAL_DB_HOST=127.0.0.1
    LOCAL_DB_PASSWORD=aa123456
    MYSQL_ROOT_PASSWORD=aa123456
    ALLOWLISTED_PLUGINS=db_dashboard
    LANGUAGE=zh

## @param resources.limits.cpu CPU limit for DB-GPT container
## @param resources.limits.memory Memory limit for DB-GPT container
##
resources:
  limits:
    cpu: 4
    memory: 8Gi

## @param persistence.enabled Enable/disable persistence using PVC
## @param persistence.size Size of the PVC
## @param persistence.storageClass Storage class for the PVC
## @param persistence.accessMode Access mode for the PVC
##
persistence:
  enabled: true
  size: 20Gi
  storageClass: ""
  accessMode: ReadWriteMany

## @param env Array of extra environment variables
##
env: []
