{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name:  {{ include "one-api.fullname" . }}
  labels:
    {{- include "one-api.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass }}
    {{- if eq "-" .Values.persistence.storageClass }}
  storageClassName: ""
    {{- else }}
  storageClassName: {{ .Values.persistence.storageClass }}
    {{- end }}
  {{- end }}
  volumeMode: {{ .Values.persistence.volumeMode }}
{{- end }}
