apiVersion: v1
kind: Service
metadata:
  name: {{ include "one-api.fullname" . }}
  labels:
    {{- include "one-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end}}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "one-api.selectorLabels" . | nindent 4 }}
