apiVersion: app.tensorstack.dev/v1beta1
kind: Template
metadata:
  name: argo-workflows
  displayName: Argo Workflows
  categories: ["Tool"]
  description: "Argo Workflows 是一个开源的工作流引擎，用于编排多步骤并行作业。"
  icon: "file://$APP_DIR/icon.png"
template:
  helm: 
    repo: "oci://docker.io/t9kpublic"
    chart: "argo-workflows"
    versions:
    - version: 0.1.1
      config: "file://$APP_DIR/configs/v0_1_1.yaml"
      urls: 
      - name: argo-workflows
        url: /apps/{{ .Release.Namespace }}/argo-workflows/{{ .Release.Name }}/
      readinessProbe:
        resources:
        - group: apps
          version: v1
          resource: deployments
          name: "{{ .Release.Name }}"
          currentStatus: "{{- range .status.conditions }}{{- if eq .type \"Available\" }}{{- .status }}{{- end }}{{- end }}"
          desiredStatus: "True" 
      dependencies:
        crds:
        - group: argoproj.io
          version: v1alpha1
          resource: workflows
