apiVersion: app.tensorstack.dev/v1beta1
kind: Template
metadata:
  name: dify
  displayName: Dify
  categories: ["AI"]
  description: "Dify 是一个开源的 LLM 应用开发平台。其直观的界面结合了 AI 工作流、RAG 管道、Agent、模型管理、可观测性功能等，让您可以快速从原型到生产。"
  icon: "file://$APP_DIR/icon.png"
template:
  helm:
    repo: "oci://docker.io/t9kpublic"
    # repo: "https://t9k.github.io/apps/"
    chart: "dify"
    versions:
    - version: 0.3.7
      urls: 
      - name: UI
        url: "http://{{ .Values.global.host }}"
      readinessProbe:
        resources:
        - group: apps
          version: v1
          resource: deployments
          name: "{{ .Release.Name }}-api"
          currentStatus: "{{- range .status.conditions }}{{- if eq .type \"Available\" }}{{- .status }}{{- end }}{{- end }}"
          desiredStatus: "True"
      dependencies: {}
