image:
  registry: ""
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

pvc: ""

resources:
  cpu: "16"
  memory: 32Gi
  gcu: "1"

ssh:
  authorizedKeys: []
  enabled: false
  serviceType: ClusterIP
