image:
  registry: ""
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

pvc: ""

resources:
  limits:
    cpu: 16
    memory: 32Gi
    enflame.com/gcu: 1

ssh:
  enabled: false
  authorizedKeys: []
  serviceType: ClusterIP

nodeSelector: []
