# Default values for nextchat.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: yidadaa/chatgpt-next-web
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: v2.12.2

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

llm:
  # 使用的模型提供商
  # 应为 "openai"、"azure"、"anthropic"" 或 "google"
  provider: "openai"
  api_key: ""
  openai:
    # 兼容 OpenAI API 的服务器的 URL
    # 如使用 OpenAI API，请设为 "https://api.openai.com"
    base_url: ""
    
  azure:
    url: ""
    api_version: ""

  anthropic:
    url: ""
    api_version: ""

  google:
    url: ""

env:
  # 代理 URL，例如 "http://127.0.0.1:7890"
  - name: PROXY_URL
    value: ""
