{{- if .Values.pluginDaemon.enabled }}
{{- if .Values.pluginDaemon.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dify.fullname" . }}-plugin-daemon-pvc
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    app.kubernetes.io/component: plugin-daemon
spec:
  accessModes:
    - {{ .Values.pluginDaemon.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.pluginDaemon.persistence.size | quote }}
  {{- if .Values.pluginDaemon.persistence.storageClass }}
  storageClassName: {{ .Values.pluginDaemon.persistence.storageClass }}
  {{- end }}
{{- end }}
{{- end }}

---
{{- if .Values.frontend.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dify.fullname" . }}-frontend-pvc
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  accessModes:
    - {{ .Values.frontend.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.frontend.persistence.size | quote }}
  {{- if .Values.frontend.persistence.storageClass }}
  storageClassName: {{ .Values.frontend.persistence.storageClass }}
  {{- end }}
{{- end }}
