apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fastgpt.fullname" . }}
  labels:
    {{- include "fastgpt.labels" . | nindent 4 }}
type: Opaque
data:
  DEFAULT_ROOT_PSW: {{ .Values.app.defaultRootPassword | toString | b64enc | quote }}
  CHAT_API_KEY: {{ .Values.app.chatApiKey | toString | b64enc | quote }}
  TOKEN_KEY: {{ .Values.app.tokenKey | toString | b64enc | quote }}
  ROOT_KEY: {{ .Values.app.rootKey | toString | b64enc | quote }}
  FILE_TOKEN_KEY: {{ .Values.app.fileTokenKey | toString | b64enc | quote }}
  MONGODB_URI: {{ printf "mongodb://%s:%s@%s-mongodb-headless:27017/fastgpt?authSource=admin" .Values.mongodb.auth.rootUser .Values.mongodb.auth.rootPassword (include "fastgpt.fullname" .) | b64enc | quote }}
  PG_URL: {{ printf "postgresql://postgres:%s@%s-postgresql:5432/%s" .Values.postgresql.global.postgresql.auth.postgresPassword (include "fastgpt.fullname" .) .Values.postgresql.global.postgresql.auth.database | b64enc | quote }}
