apiVersion: app.tensorstack.dev/v1beta1
kind: Template
metadata:
  name: redis
  displayName: "Redis"
  categories: ["Database"]
  description: "Redis is an in-memory database that persists on disk. The data model is key-value, but many different kind of values are supported: Strings, Lists, Sets, Sorted Sets, Hashes, Streams, HyperLogLogs, Bitmaps."
  icon: "file://$APP_DIR/icon.svg"
template:
  helm:
    repo: oci://registry.dockermirror.com/t9kpublic
    chart: "redis"
    versions:
    - version: 19.5.0
      urls: []
      # readinessProbe:
      #   resources:
      #   - group: apps
      #     version: v1
      #     resource: statefulset
      #     name: {{ .Release.Name }}-redis-master
      #     currentStatus: "{{- if ge .status.availableReplicas 1 }}True{{- else }}False{{- end }}"
      #     desiredStatus: "True"
      dependencies: {}
    - version: 18.19.4
      urls: []
      dependencies: {}
    - version: 17.17.1
      urls: []
      dependencies: {}
