apiVersion: tensorstack.dev/v1beta1
kind: SimpleMLService
metadata:
  name: {{ include "vllm.fullname" . }}
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  storage:
    pvc:
      {{- if .Values.model.volume.existingClaim }}
      name: {{ .Values.model.volume.existingClaim }}
      {{- else }}
      name: {{ include "vllm.fullname" . }}
      {{- end }}
      subPath: {{ .Values.model.volume.subPath }}
  service:
    type: ClusterIP
    ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  custom:
    spec:
      {{- if .Values.model.source }}
      initContainers:
        - name: wait-for-datacube
          image: bitnami/kubectl:1.27
          command: ["/bin/sh", "-c"]
          args: ["kubectl wait --for=condition=Complete datacube/{{ .Release.Name }} --timeout=-1s"]
      serviceAccount: managed-project-sa
      serviceAccountName: managed-project-sa
      {{- end }}
      containers:
      - name: server
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - --model=/var/lib/t9k/model
          - --served-model-name={{ .Values.model.deployName }}
          - --trust-remote-code
          - --tensor-parallel-size={{ (index .Values.resources.limits "nvidia.com/gpu") }}
          - --enforce-eager
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 60
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 60
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: dshm
          mountPath: /dev/shm
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: "64Gi"
