apiVersion: app.tensorstack.dev/v1beta1
kind: Template
metadata:
  name: jupyterlab-gcu
  displayName: "JupyterLab (Enflame GCU)"
  defaultVersion: "0.1.2"
  categories: 
  - IDE
  description: "JupyterLab (Enflame GCU) 是一个基于 Web 的开发环境，适用于 Enflame GCU 的计算任务。"
  icon: "file://$APP_DIR/icon.svg"
template:
  helm: 
    repo: "oci://docker.io/t9kpublic"
    chart: "jupyterlab-gcu"
    versions:
    - version: 0.2.0
      config: "file://$APP_DIR/configs/v0_2_0.yaml"
      urls: 
      - name: "jupyter"
        url: "/t9k/notebooks/projects/{{ .Release.Namespace }}/name/{{ .Release.Name }}/lab"
      readinessProbe:
        resources:
        - group: tensorstack.dev
          version: v1beta1
          resource: notebooks
          name: "{{ .Release.Name }}"
          message: "{{- range .status.conditions }}{{- if eq .type \"Ready\" }}{{- .message }}{{- end }}{{- end }}"
          currentStatus: "{{- range .status.conditions }}{{- if eq .type \"Ready\" }}{{- .status }}{{- end }}{{- end }}"
          desiredStatus: "True"
      dependencies:
        crds:
        - group: tensorstack.dev
          version: v1beta1
          resource: notebooks
    - version: 0.1.2
      config: "file://$APP_DIR/configs/v0_1_2.yaml"
      urls: 
      - name: "jupyter"
        url: "/t9k/notebooks/projects/{{ .Release.Namespace }}/name/{{ .Release.Name }}/lab"
      readinessProbe:
        resources:
        - group: tensorstack.dev
          version: v1beta1
          resource: notebooks
          name: "{{ .Release.Name }}"
          message: "{{- range .status.conditions }}{{- if eq .type \"Ready\" }}{{- .message }}{{- end }}{{- end }}"
          currentStatus: "{{- range .status.conditions }}{{- if eq .type \"Ready\" }}{{- .status }}{{- end }}{{- end }}"
          desiredStatus: "True"
      dependencies:
        crds:
        - group: tensorstack.dev
          version: v1beta1
          resource: notebooks
