apiVersion: app.tensorstack.dev/v1beta1
kind: Template
metadata:
  name: label-studio
  displayName: "Label Studio"
  categories: ["AI", "Tool"]
  description: "Label Studio is a data labeling tool."
  icon: "file://$APP_DIR/icon.png"
template:
  helm:
    repo: "oci://docker.io/t9kpublic"
    chart: "label-studio"
    versions:
    - version: 1.4.8
      urls:
      - name: UI
        url: /t9k/app/label-studio/{{ .Release.Namespace }}/{{ .Release.Name }}/
      readinessProbe:
        resources:
        - group: apps
          version: v1
          resource: deployments
          name: "{{ .Release.Name }}-ls-app"
          currentStatus: "{{- range .status.conditions }}{{- if eq .type \"Available\" }}{{- .status }}{{- end }}{{- end }}"
          desiredStatus: "True"
      dependencies: {}
