image:
  registry: docker.io
  repository: t9kpublic/autogen
  tag: "v0.4.3"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

resources:
  limits:
    cpu: 2
    memory: 4Gi
