image:
  registry: "$(T9K_APP_IMAGE_REGISTRY)"
  repository: "$(T9K_APP_IMAGE_NAMESPACE)/one-api"
  tag: "v0.6.7"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 1
    memory: 2Gi

persistence:
  enabled: true
  size: 500Mi
  storageClass: ""
  accessMode: ReadWriteMany
  volumeMode: Filesystem
  existingClaim: ""

mysql:
  enabled: true
  image:
    registry: "$(T9K_APP_IMAGE_REGISTRY)"
    repository: "$(T9K_APP_IMAGE_NAMESPACE)/mysql"
    tag: 5.7.43
  auth:
    database: oneapi
    rootPassword: "123456"
  primary:
    resources:
      limits:
        cpu: 1
        memory: 2Gi
    persistence:
      enabled: true
