## @param pvc Select a pvc as File Browser workspace.
pvc: ""

## @param resources.limits.cpu CPU limit for the App container
## @param resources.limits.memory Memory limit for the App container
resources:
  limits:
    cpu: 100m
    memory: 200Mi
