## @param pvc Mount a pvc as File Browser workspace
pvc: ""

## @param resources.limits.cpu CPU limit for File Browser container
## @param resources.limits.memory Memory limit for File Browser container
resources:
  limits:
    cpu: 100m
    memory: 200Mi
