## @param replicaCount Number of replicas for the deployment
##
replicaCount: 1

## @param image.registry [default: docker.io] Repository registry for the Docker image
## @param image.repository [default: yidadaa/chatgpt-next-web] Repository name for the Docker image
## @param image.tag Image tag for the Docker image (immutable tags are recommended)
## @param image.pullPolicy Image pull policy for the Docker image
##
image:
  registry: docker.io
  repository: yidadaa/chatgpt-next-web
  tag: v2.12.2
  pullPolicy: IfNotPresent

## @param service.type Service type for the Kubernetes service
## @param service.port Port for the Kubernetes service
##
service:
  type: ClusterIP
  port: 3000

## @param ingress.enabled Enable/disable Kubernetes ingress
## @param ingress.className Ingress class name
## @param ingress.annotations Annotations for Kubernetes ingress
## @param ingress.hosts List of hosts for Kubernetes ingress
## @param ingress.tls TLS configuration for Kubernetes ingress
##
ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

## @param resources.limits.cpu CPU limit for Kubernetes resources
## @param resources.limits.memory Memory limit for Kubernetes resources
##
resources:
  limits:
    cpu: 1
    memory: 2Gi

## @param llm.provider Provider of the language model (`openai`, `azure`, `anthropic`, or `google`)
## @param llm.api_key API key for the language model provider
## @param llm.openai.base_url Base URL for OpenAI API-compatible servers
## @param llm.azure.url URL for Azure language model API
## @param llm.azure.api_version API version for Azure language model API
## @param llm.anthropic.url URL for Anthropic language model API
## @param llm.anthropic.api_version API version for Anthropic language model API
## @param llm.google.url URL for Google language model API
##
llm:
  # 使用的模型提供商
  # 应为 "openai"、"azure"、"anthropic"" 或 "google"
  provider: "openai"
  api_key: "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"
  openai:
    # 兼容 OpenAI API 的服务器的 URL
    # 如使用 OpenAI API，请设为 "https://api.openai.com"
    base_url: "https://api.openai-proxy.com"
    
  azure:
    url: ""
    api_version: ""

  anthropic:
    url: ""
    api_version: ""

  google:
    url: ""

## @param env Array of extra environment variables
##
env: []
  # # 代理 URL，例如 "http://127.0.0.1:7890"
  # - name: PROXY_URL
  #   value: ""
