apiVersion: app.tensorstack.dev/v1beta1
kind: Template
metadata:
  name: vllm
  displayName: vLLM
  categories: ["AI"]
  description: "vLLM 是一个高吞吐量和内存高效的 LLM 推理和服务引擎。"
  icon: "file://$APP_DIR/icon.png"
template:
  helm:
    repo: "oci://docker.io/t9kpublic"
    # repo: "https://t9k.github.io/apps/"
    chart: "vllm"
    versions:
    - version: 0.3.2
      config: "file://$APP_DIR/configs/v0_3_2.yaml"
      urls: []
      readinessProbe:
        resources:
        - group: tensorstack.dev
          version: v1beta1
          resource: mlservices
          name: "{{ .Release.Name }}"
          currentStatus: "{{- range .status.conditions }}{{- if eq .type \"Ready\" }}{{- .status }}{{- end }}{{- end }}"
          desiredStatus: "True"
      dependencies:
        crds:
        - group: tensorstack.dev
          version: v1beta1
          resource: mlservices
        - group: tensorstack.dev
          version: v1beta1
          resource: datacubes
