apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    component: service-manager-web
spec:
  hosts:
    - '*'
  gateways:
    - {{ .Values.network.gateway }}
  http:
    - match:
        - uri:
            prefix: /apps/{{ .Release.Namespace }}/service-manager/{{ .Release.Name }}/web/
      rewrite:
        uri: /
    {{- if .Values.authorization.enabled }}
      headers:
        request:
          add:
            x-auth-request-redirect: /apps/{{ .Release.Namespace }}/service-manager/{{ .Release.Name }}/web/
    {{- end }}
      route:
        - destination:
            host: {{ .Release.Name }}-web
            port:
              number: 8080
