apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    component: service-manager-web
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: service-manager-web
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: service-manager-web
    spec:
      containers:
        - name: service-manager-web
          image: {{ include "serviceManagerWeb.image" . }}
          ports:
            - name: http
              containerPort: 8080
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          resources:
            limits:
              cpu: 500m
              memory: 300Mi
            requests:
              cpu: 50m
              memory: 100Mi
          volumeMounts:
            - name: web-config
              mountPath: /app/web-asset/config
      {{- if .Values.authorization.enabled }}
        - command: ["/app/pep-proxy"]
          args:
          - --http-address=0.0.0.0:4180
          - --upstream=http://127.0.0.1:8080/
          - --client-id={{ .Values.authorization.clientID }}
          - --redeem-url={{ .Values.network.domain.home }}/t9k/security/server/apis/v1/login/auth-code
          - --redirect-url={{ .Values.network.domain.home }}/apps/{{ .Release.Namespace }}/service-manager/{{ .Release.Name }}/web/oauth2/callback
          - --oidc-issuer-url={{ .Values.network.domain.auth }}/auth/realms/t9k-realm
          - --security-server-address={{ .Values.network.domain.home }}/t9k/security/server
          - --pep-config=/t9kconfig/pep-config.yaml
          image: {{ include "pepProxy.image" . }}
          imagePullPolicy: {{ .Values.authorization.pepProxy.image.pullPolicy }}
          name: pep-proxy
          ports:
          - containerPort: 4180
            name: proxy
          resources:
            limits:
              cpu: 500m
              memory: 300Mi
            requests:
              cpu: 10m
              memory: 50Mi
          volumeMounts:
            - name: pep-config
              mountPath: /t9kconfig
      {{- end }}
      volumes:
        - name: web-config
          configMap:
            name: {{ .Release.Name }}-web-config
    {{- if .Values.authorization.enabled }}
        - name: pep-config
          configMap:
            name: pep-config-{{ .Release.Name }}
    {{- end }}