apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    component: service-manager-web
spec:
  selector:
    app: {{ .Release.Name }}
    component: service-manager-web
  ports:
    - name: http
      port: 8080
    {{- if .Values.authorization.enabled }}
      targetPort: 4180
    {{- else }}
      targetPort: 8080
    {{- end }}