## @param image.registry Stable Diffusion Webui image registry
## @param image.repository Stable Diffusion Webui image repository
## @param image.tag Stable Diffusion Webui image tag
## @param image.pullPolicy Stable Diffusion Webui image pull policy
##
image:
  registry: "$(T9K_APP_IMAGE_REGISTRY)"
  repository: "$(T9K_APP_IMAGE_NAMESPACE)/stable-diffusion-webui"
  tag: "20240514"
  pullPolicy: IfNotPresent

## @param resources.limits.cpu CPU limit for Stable Diffusion Webui container
## @param resources.limits.memory Memory limit for Stable Diffusion Webui container
## @param resources.limits."nvidia.com/gpu" NVIDIA GPU limit for Stable Diffusion Webui container
##
resources:
  limits:
    cpu: 4
    memory: 64Gi
    nvidia.com/gpu: 1

## @param persistence.size Size of the PVC
## @param persistence.storageClass Storage class for the PVC
## @param persistence.accessModes Access modes for the PVC
## @param persistence.existingClaim Name of an existing PVC to use
##
persistence:
  size: 64Gi
  storageClass: ""
  accessModes:
  - ReadWriteOnce
  existingClaim: ""
