---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: csi-cephfs-secret
stringData:
  # Required for dynamically provisioned volumes
  adminID: {{ .Values.ceph.adminID }}
  adminKey: {{ .Values.ceph.adminKey }}
