## @param image.registry AnythingLLM image registry
## @param image.repository AnythingLLM image repository
## @param image.tag AnythingLLM image tag
## @param image.pullPolicy AnythingLLM image pull policy
##
image:
  registry: "$(T9K_APP_IMAGE_REGISTRY)"
  repository: "$(T9K_APP_IMAGE_NAMESPACE)/anythingllm"
  tag: "1.7.4"
  pullPolicy: IfNotPresent

## @param resources.limits.cpu CPU limit for AnythingLLM container
## @param resources.limits.memory Memory limit for AnythingLLM container
##
resources:
  limits:
    cpu: 4
    memory: 8Gi

## @param storage.size Storage size for AnythingLLM data
##
storage:
  size: 10Gi
