## @param image.registry Docker registry for the image
## @param image.repository Repository name for the image
## @param image.tag Tag for the image version
##
image:
  registry: "$(T9K_APP_IMAGE_REGISTRY)"
  repository: "$(T9K_APP_IMAGE_NAMESPACE)/comfyui"
  tag: "20240709"

## @param resources.limits.cpu CPU limit for Kubernetes resources
## @param resources.limits.memory Memory limit for Kubernetes resources
## @param resources.limits."nvidia.com/gpu" NVIDIA GPU limit for Kubernetes resources
##
resources:
  limits:
    cpu: 4
    memory: 64Gi
    nvidia.com/gpu: 1

## @param persistence.size Size of the persistent volume claim
##
persistence:
  size: 32Gi

## @param env Array of extra environment variables
##
env: []
  # # HTTP 和 HTTPS 代理
  # - name: http_proxy
  #   value: ""
  # - name: https_proxy
  #   value: ""
