authorization:
  enabled: true
  clientID: "t9k-client"
  pepProxy:
    image:
      registry: "docker.io"
      repository: "t9kpublic/pep-proxy"
      tag: "1.0.14"
    imagePullPolicy: Always

network:
  gateway: project-gateway
  domain:
    home: "https://home.sample.t9kcloud.cn"
    auth: "https://auth.sample.t9kcloud.cn"

server:
  serviceAccount: managed-project-sa
  imagePullPolicy: IfNotPresent
  image:
    registry: "docker.io"
    repository: "t9kpublic/job-manager-server"
    tag: "240805"
  
web:
  serviceAccount: default
  imagePullPolicy: IfNotPresent
  image:
    registry: "docker.io"
    repository: "t9kpublic/job-manager-web"
    tag: "240805"

cluster:
  extendedResources:
    gpu: ["nvidia.com/gpu.shared", "nvidia.com/gpu"]

t9kScheduler:
  enabled: false

kueue:
  enabled: false
