authorization:
  enabled: true
  clientID: "t9k-client"
  pepProxy:
    image: "registry.cn-hangzhou.aliyuncs.com/t9k/pep-proxy:1.0.12"
    imagePullPolicy: Always

network:
  gateway: project-gateway
  domain:
    home: "https://home.sample.t9kcloud.cn"
    auth: "https://auth.sample.t9kcloud.cn"

server:
  serviceAccount: managed-project-sa
  imagePullPolicy: IfNotPresent
  image: "registry.cn-hangzhou.aliyuncs.com/t9k/job-manager-server:240715"
  
web:
  serviceAccount: default
  imagePullPolicy: IfNotPresent
  image: "registry.cn-hangzhou.aliyuncs.com/t9k/job-manager-web:240715"

cluster:
  extendedResources:
    gpu: ["nvidia.com/gpu.shared", "nvidia.com/gpu"]
