authorization:
  enabled: true
  clientID: "t9k-client"
  pepProxy:
    image: "docker.io/t9kpublic/pep-proxy:1.0.12"
    imagePullPolicy: Always

network:
  gateway: project-gateway
  domain:
    home: "https://home.example.t9kcloud.cn"
    auth: "https://auth.example.t9kcloud.cn"

server:
  serviceAccount: managed-project-sa
  imagePullPolicy: Always
  image: "docker.io/t9kpublic/job-manager-server:240712"
  
web:
  serviceAccount: default
  imagePullPolicy: Always
  image: "docker.io/t9kpublic/job-manager-web:240712"

cluster:
  extendedResources:
    gpu: ["nvidia.com/gpu.shared", "nvidia.com/gpu"]
