## @param image.registry Repository registry for the Docker image
## @param image.repository Repository name for the Docker image
## @param image.tag Image tag for the Docker image (immutable tags are recommended)
## @param image.pullPolicy Image pull policy for the Docker image
##
image:
  registry: "$(T9K_APP_IMAGE_REGISTRY)"
  repository: "$(T9K_APP_IMAGE_NAMESPACE)/code-server"
  tag: "20240920"
  pullPolicy: IfNotPresent

## @param pvc Mount a PVC as Code Server workspace
pvc: ""

## @param resources.limits.cpu CPU limit for the App container
## @param resources.limits.memory Memory limit for the App container
## @param resources.limits."nvidia.com/gpu" NVIDIA GPU limit for the App container
resources:
  limits:
    cpu: 16
    memory: 32Gi
    nvidia.com/gpu: 1
