apiVersion: tensorstack.dev/v1beta1
kind: Notebook
metadata:
  name: tutorial
spec:
  type: rstudio
  template:
    spec:
      containers:
        - name: notebook
          image: t9kpublic/rocker-4.2.3-rstudio:1.72.1
          volumeMounts:
            - name: workingdir
              mountPath: /t9k/mnt/workspace
          ## @param spec.template.spec.containers[0].resources.requests.cpu The minimum number of CPU the notebook requests.
          ## @param spec.template.spec.containers[0].resources.requests.memory The minimum number of memory the notebook requests.
          ## @param spec.template.spec.containers[0].resources.limits.cpu The maximum number of CPU the notebook can use.
          ## @param spec.template.spec.containers[0].resources.limits.memory The maximum number of CPU the notebook can use.
          resources:
            requests:
              cpu: "8"
              memory: 16Gi
            limits:
              cpu: "16"
              memory: 32Gi
      volumes:
        - name: workingdir
          persistentVolumeClaim:
            ## @param spec.template.spec.volumes[0].persistentVolumeClaim.claimName Mount a pvc as notebook working directory.
            claimName: tutorial