apiVersion: tensorstack.dev/v1beta1
kind: SimpleMLService
metadata:
  name: {{ include "vllm.fullname" . }}
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- if .Values.t9k.queue }}
  scheduler:
    t9kScheduler:
      queue: {{ .Values.t9k.queue }}
  {{- end }}
  storage:
    pvc:
      name: {{ .Values.model.existingClaim }}
      subPath: {{ .Values.model.subPath }}
  service:
    type: ClusterIP
    ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  custom:
    spec:
      containers:
      - name: server
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - --model=/var/lib/t9k/model
          - --served-model-name={{ .Values.model.deployName }}
          - --trust-remote-code
        ports:
        - containerPort: 8000
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
