apiVersion: tensorstack.dev/v1beta1
kind: Notebook
metadata:
  name: "{{ .Release.Name }}"
spec:
  type: rstudio
  template:
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector: {{ toJson .Values.nodeSelector }}
      {{- end}}
      containers:
        - name: notebook
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: workingdir
              mountPath: /t9k/mnt/workspace
            {{- range.Values.volumes.extraVolumes }}
            - name: {{ .volume.name }}
              mountPath: {{ .mountPath }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: workingdir
          persistentVolumeClaim:
            claimName: "{{ .Values.volumes.workingDir.pvc }}"
        {{- range .Values.volumes.extraVolumes }}
        - {{ toYaml .volume | nindent 10 | trim }}
        {{- end }}
  ssh:
  {{- if .Values.ssh.authorizedKeys }}
    authorized_keys: {{ toYaml .Values.ssh.authorizedKeys | nindent 4}}
  {{- else }}
    authorized_keys: []
  {{- end }}
    enabled: {{ .Values.ssh.enabled }}
    serviceType: "{{ .Values.ssh.serviceType }}"
