apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gpt-researcher.fullname" . }}
  labels:
    {{- include "gpt-researcher.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gpt-researcher.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gpt-researcher.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 15
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 15
            failureThreshold: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env: 
            {{- include "gpt-researcher.envs" . | nindent 12 }}
            {{- if gt (len .Values.env) 0 }}
            {{- toYaml .Values.env | nindent 12 }}
            {{- end }}
            {{- if .Values.docs.enabled }}
            - name: DOC_PATH
              value: "/home/gpt-researcher/docs"
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "gpt-researcher.fullname" . }}
      {{- if .Values.docs.enabled }}
          volumeMounts:
            - name: data
              mountPath: /home/gpt-researcher/docs
              subPath: {{ .Values.docs.volume.subPath }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.docs.volume.existingClaim }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
