apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gpt-researcher.fullname" . }}
  labels:
    {{- include "gpt-researcher.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if eq .Values.llm.provider "openai" }}
  OPENAI_API_KEY: {{ .Values.llm.apiKey | toString | b64enc | quote }}  
  {{- end }}
  {{- if eq .Values.retriever.provider "BingSearch" }}
  BING_API_KEY: {{ .Values.retriever.apiKey | toString | b64enc | quote }}
  {{- else if eq .Values.retriever.provider "google" }}
  GOOGLE_API_KEY: {{ .Values.retriever.apiKey | toString | b64enc | quote }}
  {{- else if eq .Values.retriever.provider "searx" }}
  SEARX_URL: {{ .Values.retriever.apiKey | toString | b64enc | quote }}
  {{- else if eq .Values.retriever.provider "serpapi" }}
  SERPAPI_API_KEY: {{ .Values.retriever.apiKey | toString | b64enc | quote }}
  {{- else if eq .Values.retriever.provider "googleSerp" }}
  SERPER_API_KEY: {{ .Values.retriever.apiKey | toString | b64enc | quote }}
  {{- else if eq .Values.retriever.provider "tavily" }}
  TAVILY_API_KEY: {{ .Values.retriever.apiKey | toString | b64enc | quote }}
  {{- end }}
