apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gpt-researcher.fullname" . }}
  labels:
    {{- include "gpt-researcher.labels" . | nindent 4 }}
type: Opaque
data:
  OPENAI_API_KEY: {{ .Values.llm.apiKey | toString | b64enc | quote }}  
  {{- if eq .Values.retriever.provider "bing" }}
  BING_API_KEY: {{ .Values.retriever.apiKey | toString | b64enc | quote }}
  {{- else if eq .Values.retriever.provider "google" }}
  GOOGLE_API_KEY: {{ .Values.retriever.apiKey | toString | b64enc | quote }}
  {{- else if eq .Values.retriever.provider "searchapi" }}
  SEARCHAPI_API_KEY: {{ .Values.retriever.apiKey | toString | b64enc | quote }}
  {{- else if eq .Values.retriever.provider "serpapi" }}
  SERPAPI_API_KEY: {{ .Values.retriever.apiKey | toString | b64enc | quote }}
  {{- else if eq .Values.retriever.provider "serper" }}
  SERPER_API_KEY: {{ .Values.retriever.apiKey | toString | b64enc | quote }}
  {{- else if eq .Values.retriever.provider "searx" }}
  SEARX_URL: {{ .Values.retriever.apiKey | toString | b64enc | quote }}
  {{- else if eq .Values.retriever.provider "exa" }}
  EXA_API_KEY: {{ .Values.retriever.apiKey | toString | b64enc | quote }}
  {{- else }}
  TAVILY_API_KEY: {{ .Values.retriever.apiKey | toString | b64enc | quote }}
  {{- end }}
