authorization:
  enabled: true
  clientID: "t9k-client"
  pepProxy:
    image:
      registry: "docker.io"
      repository: "t9kpublic/pep-proxy"
      tag: "1.0.14"
    imagePullPolicy: IfNotPresent

network:
  gateway: project-gateway
  domain:
    home: "https://home.sample.t9kcloud.cn"
    auth: "https://auth.sample.t9kcloud.cn"

app:
  serviceAccount: managed-project-sa
  image:
    registry: "docker.io"
    repository: "t9kpublic/workflow-app"
    tag: "240830"
  imagePullPolicy: IfNotPresent

docs: "https://t9k.github.io/ucman/latest/api/workflow/index.html"
