## @param image.registry Repository registry for the Docker image
## @param image.repository Repository name for the Docker image
## @param image.tag Image tag for the Docker image (immutable tags are recommended)
## @param image.pullPolicy Image pull policy for the Docker image
##
image:
  registry: docker.io
  repository: t9kpublic/torch-2.1.0-notebook
  tag: "20240716"
  pullPolicy: IfNotPresent

## @param[required] pvc Mount a pvc as notebook working directory.
pvc: ""

## @param resources.cpu The maximum number of CPU the notebook can use.
## @param resources.memory The maximum number of CPU the notebook can use.
resources:
  cpu: "16"
  memory: 32Gi

## @param ssh.enabled Set true to start a SSH Service for the notebook.
## @param ssh.authorizedKeys A list of names of v1.Secret containing SSH public keys authorized for access to this SSH service.
#
# ssh:
#   enabled: true
#   authorizedKeys:
#   - "secret-name"
ssh:
  enabled: false
  authorizedKeys: []
