## @param image.registry RStudio image registry
## @param image.repository RStudio image repository
## @param image.tag RStudio image tag
## @param image.pullPolicy RStudio image pull policy
##
image:
  registry: docker.io
  repository: t9kpublic/rocker-4.2.3-rstudio
  tag: "1.72.1"
  pullPolicy: IfNotPresent

## @param[required] pvc Mount a pvc as RStudio workspace
pvc: ""

## @param resources.limits.cpu CPU limit for RStudio container
## @param resources.limits.memory Memory limit for RStudio container
resources:
  limits:
    cpu: 16
    memory: 32Gi

## @param ssh.enabled Set true to start a SSH Service for RStudio
## @param ssh.authorizedKeys A list of names of v1.Secret containing SSH public keys authorized for access to this SSH service
## @param ssh.serviceType Type for the SSH service (`ClusterIP` or `NodePort`)
#
# ssh:
#   enabled: true
#   authorizedKeys:
#   - "secret-name"
#   serviceType: ClusterIP
#
ssh:
  enabled: false
  authorizedKeys: []
  serviceType: ClusterIP
