## @param image.registry Repository registry for the Docker image
## @param image.repository Repository name for the Docker image
## @param image.tag Image tag for the Docker image (immutable tags are recommended)
## @param image.pullPolicy Image pull policy for the Docker image
##
image:
  registry: docker.io
  repository: t9kpublic/rocker-4.2.3-rstudio
  tag: "1.72.1"
  pullPolicy: IfNotPresent

## @param pvc Mount a pvc as RStudio working directory
pvc: ""

## @param resources.cpu The maximum number of CPU the RStudio can use
## @param resources.memory The maximum number of CPU the RStudio can use
resources:
  limits:
    cpu: 16
    memory: 32Gi

## @param ssh.enabled Set true to start a SSH Service for RStudio
## @param ssh.authorizedKeys A list of names of v1.Secret containing SSH public keys authorized for access to this SSH service
## @param ssh.serviceType Type for the SSH service (`ClusterIP` or `NodePort`)
#
# ssh:
#   enabled: true
#   authorizedKeys:
#   - "secret-name"
#   serviceType: ClusterIP
#
ssh:
  enabled: false
  authorizedKeys: []
  serviceType: ClusterIP
