kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "comfyui.fullname" . }}
  labels:
  {{- include "comfyui.labels" . | nindent 4 }}
spec:
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass -}}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  accessModes:
  {{- toYaml .Values.persistence.accessModes | nindent 4 }}
