image:
  registry: docker.io
  repository: justsong/one-api
  tag: ""
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 1
    memory: 2Gi

persistence:
  enabled: false
  size: 500Mi
  storageClass: ""
  accessMode: ReadWriteMany
  volumeMode: Filesystem
  existingClaim: ""

env:
  SQL_DSN: ""
  TZ: Asia/Shanghai

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

nodeSelector: {}
affinity: {}
tolerations: []

# sub-charts
mysql:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/mysql
    tag: 5.7.43
  auth:
    database: oneapi
    rootPassword: "123456"
  primary:
    resources:
      limits:
        cpu: 1
        memory: 2Gi
    persistence:
      enabled: true
