## @param image.registry ChatNio image registry
## @param image.repository ChatNio image repository
## @param image.tag ChatNio image tag
## @param image.pullPolicy ChatNio image pull policy
##
image:
  registry: "$(T9K_APP_IMAGE_REGISTRY)"
  repository: "$(T9K_APP_IMAGE_NAMESPACE)/chatnio"
  tag: "20241109"
  pullPolicy: IfNotPresent

## @param resources.limits.cpu CPU limit for ChatNio container
## @param resources.limits.memory Memory limit for ChatNio container 
##
resources:
  limits:
    cpu: 1
    memory: 2Gi

## @param persistence.enabled Enable/disable persistence using PVC
## @param persistence.size Size of the PVC
## @param persistence.storageClass Storage class for the PVC
## @param persistence.accessMode Access mode for the PVC
## @param persistence.existingClaim Name of an existing PVC to use
##
persistence:
  enabled: true
  size: 1Gi
  storageClass: ""
  accessMode: ReadWriteMany
  existingClaim: ""

## @param mysql.enabled Enable/disable installation of MySQL
##
mysql:
  enabled: true

  ## @param mysql.image.registry MySQL image registry
  ## @param mysql.image.repository MySQL image repository
  ## @param mysql.image.tag MySQL image tag
  ## @param mysql.image.pullPolicy MySQL image pull policy
  ##
  image:
    registry: "$(T9K_APP_IMAGE_REGISTRY)"
    repository: "$(T9K_APP_IMAGE_NAMESPACE)/mysql"
    tag: 5.7.43
    pullPolicy: IfNotPresent
  
  ## @param mysql.auth.database MySQL database name
  ## @param mysql.auth.username MySQL username
  ## @param mysql.auth.password MySQL user password
  ## @param mysql.auth.rootPassword MySQL root password
  ##
  auth:
    database: chatnio
    username: chatnio
    password: chatnio123456!
    rootPassword: root
  
  ## @param mysql.primary.resources.limits.cpu CPU limit for MySQL container
  ## @param mysql.primary.resources.limits.memory Memory limit for MySQL container
  ## @param mysql.primary.persistence.enabled Enable persistence for MySQL
  ##
  primary:
    resources:
      limits:
        cpu: 1
        memory: 2Gi
    persistence:
      enabled: true

## @param redis.enabled Enable/disable Redis installation
## @param redis.auth.enabled Enable/disable Redis authentication
## @param redis.master.persistence.enabled Enable persistence for Redis
##
redis:
  enabled: true

  ## @param redis.image.registry Redis image registry
  ## @param redis.image.repository Redis image repository
  ## @param redis.image.tag Redis image tag
  ## @param redis.image.pullPolicy Redis image pull policy
  ##
  image:
    registry: "$(T9K_APP_IMAGE_REGISTRY)"
    repository: "$(T9K_APP_IMAGE_NAMESPACE)/redis"
    tag: 7.4.1
    pullPolicy: IfNotPresent

  auth:
    enabled: false
  master:
    persistence:
      enabled: true
