## @param image.registry Code Server image registry
## @param image.repository Code Server image repository
## @param image.tag Code Server image tag
## @param image.pullPolicy Code Server image pull policy
##
image:
  registry: "$(T9K_APP_IMAGE_REGISTRY)"
  repository: "$(T9K_APP_IMAGE_NAMESPACE)/code-server"
  tag: "20241023"
  pullPolicy: IfNotPresent

## @param pvc Mount a PVC as Code Server workspace
pvc: ""

## @param resources.limits.cpu CPU limit for Code Server container
## @param resources.limits.memory Memory limit for Code Server container
## @param resources.limits."nvidia.com/gpu" NVIDIA GPU limit for Code Server container
resources:
  limits:
    cpu: 16
    memory: 32Gi
    nvidia.com/gpu: 1
