## @param image.registry TensorBoard image registry
## @param image.repository TensorBoard image repository
## @param image.tag TensorBoard image tag
## @param image.pullPolicy TensorBoard image pull policy
##
image:
  registry: "$(T9K_APP_IMAGE_REGISTRY)"
  repository: "$(T9K_APP_IMAGE_NAMESPACE)/tensorboard"
  tag: "2.17.0"
  pullPolicy: IfNotPresent

## @param logDir Read tensorboard logs from pvc or s3 storage.
# logDir:
#   pvc:
#     - name: tutorial
#       subPath:
#         - "train/logs"
#   s3:
#     secretRef:
#       name: ""
#     uri:
#       - ""
logDir: {}

## @param resources.limits.cpu CPU limit for TensorBoard container
## @param resources.limits.memory Memory limit for TensorBoard container
resources:
  limits:
    cpu: 200m
    memory: 4Gi
