## @param image.registry Repository registry for the Docker image
## @param image.repository Repository name for the Docker image
## @param image.tag Image tag for the Docker image (immutable tags are recommended)
## @param image.pullPolicy Image pull policy for the Docker image
##
image:
  registry: "$(T9K_APP_IMAGE_REGISTRY)"
  repository: "$(T9K_APP_IMAGE_NAMESPACE)/tensorboard"
  tag: "2.17.0"
  pullPolicy: IfNotPresent

## @param logDir Read tensorboard logs from pvc or s3 storage.
# logDir:
#   pvc:
#     - name: tutorial
#       subPath:
#         - "train/logs"
#   s3:
#     secretRef:
#       name: ""
#     uri:
#       - ""
logDir: {}

## @param resources.limits.cpu CPU limit for the App container
## @param resources.limits.memory Memory limit for the App container
resources:
  limits:
    cpu: 200m
    memory: 4Gi
