apiVersion: app.tensorstack.dev/v1beta1
kind: Template
metadata:
  name: vllm-enflame
  displayName: vLLM (Enflame GCU)
  categories: ["AI"]
  description: "vLLM 是一个高吞吐量和内存高效的 LLM 推理和服务引擎。"
  icon: "file://$APP_DIR/icon.png"
template:
  helm:
    repo: "oci://registry.qingyang.t9kcloud.cn/t9kcharts"
    # repo: "https://t9k.github.io/apps/"
    chart: "vllm-enflame"
    versions:
    - version: 0.3.0
      config: "file://$APP_DIR/configs/v0_3_0.yaml"
      urls: []
      readinessProbe:
        resources:
        - group: tensorstack.dev
          version: v1beta1
          resource: mlservices
          name: "{{ .Release.Name }}"
          currentStatus: "{{- range .status.conditions }}{{- if eq .type \"Ready\" }}{{- .status }}{{- end }}{{- end }}"
          desiredStatus: "True"
      dependencies: {}
