apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nextchat.fullname" . }}
  labels:
    {{- include "nextchat.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if eq .Values.llm.provider "openai" }}
  OPENAI_API_KEY: {{ .Values.llm.api_key | toString | b64enc | quote }}
  {{- else if eq .Values.llm.provider "azure" }}
  AZURE_API_KEY: {{ .Values.llm.api_key | toString | b64enc | quote }}
  {{- else if eq .Values.llm.provider "anthropic" }}
  ANTHROPIC_API_KEY: {{ .Values.llm.api_key | toString | b64enc | quote }}
  {{- else if eq .Values.llm.provider "google" }}
  GOOGLE_API_KEY: {{ .Values.llm.api_key | toString | b64enc | quote }}
  {{- end }}
