## @param image.registry Repository registry for the Docker image
## @param image.repository Repository name for the Docker image
## @param image.tag Image tag for the Docker image (immutable tags are recommended)
## @param image.pullPolicy Image pull policy for the Docker image
##
image:
  registry: docker.io
  repository: t9kpublic/rocker-4.2.3-rstudio
  tag: "1.72.1"
  pullPolicy: IfNotPresent

## @param[required] pvc Mount a pvc as notebook working directory.
pvc: ""

## @param resources.cpu The maximum number of CPU the notebook can use.
## @param resources.memory The maximum number of CPU the notebook can use.
resources:
  cpu: "16"
  memory: 32Gi
