# +t9k:form:pattern v2

network:
  domain:
    home: "$(T9K_HOME_DOMAIN)"
    auth: "$(T9K_AUTH_DOMAIN)"

cluster:
  extendedResources:
    gpu: ["nvidia.com/gpu.shared", "nvidia.com/gpu"]

# +t9k:description:en AutoTune Console image config.
# +t9k:description:zh AutoTune Console 镜像信息。
image:
  # +t9k:form
  # +t9k:description:en AutoTune Console image registry.
  # +t9k:description:zh AutoTune Console 镜像仓库。 
  registry: "$(T9K_APP_IMAGE_REGISTRY)"
  # +t9k:form
  # +t9k:description:en AutoTune Console image repository.
  # +t9k:description:zh AutoTune Console 镜像名称。
  repository: "$(T9K_APP_IMAGE_NAMESPACE)/autotune-app"
  # +t9k:form
  # +t9k:description:en AutoTune Console image tag.
  # +t9k:description:zh AutoTune Console 镜像标签。
  tag: "240822"

authorization:
  pepProxy:
    image:
      registry: "$(T9K_APP_IMAGE_REGISTRY)"
      repository: "$(T9K_APP_IMAGE_NAMESPACE)/pep-proxy"
      tag: "1.0.12"
