# +t9k:form:pattern v2

# +t9k:description:en Fish Speech image config.
# +t9k:description:zh Fish Speech 镜像信息。
image:
  # +t9k:form
  # +t9k:description:en Fish Speech image registry.
  # +t9k:description:zh Fish Speech 镜像仓库。 
  registry: "$(T9K_APP_IMAGE_REGISTRY)"
  # +t9k:form
  # +t9k:description:en Fish Speech image repository.
  # +t9k:description:zh Fish Speech 镜像名称。
  repository: "$(T9K_APP_IMAGE_NAMESPACE)/fish-speech"
  # +t9k:form
  # +t9k:description:en Fish Speech image tag.
  # +t9k:description:zh Fish Speech 镜像标签。
  tag: "v1.5.0"
  pullPolicy: IfNotPresent

resources:
  # +t9k:description:en App resource limit.
  # +t9k:description:zh App 资源限额。
  limits:
    # +t9k:form
    # +t9k:description:en CPU limit for the App container.
    # +t9k:description:zh App CPU 限制。
    cpu: 1    
    # +t9k:form
    # +t9k:description:en Memory limit for the App container.
    # +t9k:description:zh App 内存限制。
    memory: 4Gi
    # +t9k:form
    # +t9k:description:en NVIDIA GPU limit for App container.
    # +t9k:description:zh App Nvidia GPU 限制。
    nvidia.com/gpu: 1

