apiVersion: app.tensorstack.dev/v1beta1
kind: Template
metadata:
  name: search-with-lepton
  displayName: "Search with Lepton"
  category: ["AI"]
  description: "Search with Lepton 是一个开源的对话式搜索引擎（conversational search engine）。"
  icon: "file://$APP_DIR/icon.png"
template:
  helm:
    repo: "oci://docker.io/t9kpublic"
    chart: "search-with-lepton"
    versions:
    - version: 0.1.1
      urls: 
      - name: UI
        url: /t9k/app/search-with-lepton/{{ .Release.Namespace }}/{{ .Release.Name }}/
      # readinessProbe:
      #   resources:
      #   - group: apps
      #     version: v1
      #     resource: deployments
      #     name: terminal-{{ .Release.Name }}
      #     currentStatus: "{{- range .status.conditions }}{{- if eq .type \"Available\" }}{{- .status }}{{- end }}{{- end }}"
      #     desiredStatus: "True"
      dependences: {}
