{{- if .Values.config.settings.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "searxng.fullname" . }}-settings
  labels:
    {{- include "searxng.labels" . | nindent 4 }}
data:
  settings.yml: |
    {{- tpl .Values.config.settings.data . | nindent 4 }}
{{- end }}

---
{{- if .Values.config.limiter.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "searxng.fullname" . }}-limiter
  labels:
    {{- include "searxng.labels" . | nindent 4 }}
data:
  limiter.toml: |
    {{- .Values.config.limiter.data | nindent 4 }}
{{- end }}

---
{{- if .Values.config.uwsgi.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "searxng.fullname" . }}-uwsgi
  labels:
    {{- include "searxng.labels" . | nindent 4 }}
data:
  uwsgi.ini: |
    {{- .Values.config.uwsgi.data | nindent 4 }}
{{- end }}
