apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "searxng.fullname" . }}
  labels:
    {{- include "searxng.labels" . | nindent 4 }}
spec:
  gateways:
  - project-gateway
  hosts:
  - '*'
  http:
  - headers:
      request:
        remove: 
        - cookie
    match:
    - uri:
        prefix: /apps/{{ .Release.Namespace }}/searxng/{{ .Release.Name }}/
    rewrite:
      uri: /
    route:
    - destination:
        host: {{ .Release.Name }}
        port:
          number: {{ .Values.service.port }}
