annotations:
  artifacthub.io/category: ai-machine-learning
  artifacthub.io/changes: |
    - kind: added
      description: add support for initContainers
    - kind: added
      description: add annotation to service
apiVersion: v2
appVersion: 0.1.41
description: Get up and running with large language models locally.
home: https://ollama.ai/
icon: https://ollama.ai/public/ollama.png
keywords:
- ai
- llm
- llama
- mistral
kubeVersion: ^1.16.0-0
maintainers:
- email: tech@outworld.fr
  name: Outworld
name: ollama
sources:
- https://github.com/ollama/ollama
- https://github.com/otwld/ollama-helm
type: application
version: 0.29.2
