## @param image.registry Fish Speech image registry
## @param image.repository Fish Speech image repository
## @param image.tag Fish Speech image tag
## @param image.pullPolicy Fish Speech image pull policy
##
image:
  registry: "$(T9K_APP_IMAGE_REGISTRY)"
  repository: "$(T9K_APP_IMAGE_NAMESPACE)/fish-speech"
  tag: "v1.5.0"
  pullPolicy: IfNotPresent

## @param resources.limits.cpu CPU limit for Fish Speech container
## @param resources.limits.memory Memory limit for Fish Speech container
## @param resources.limits."nvidia.com/gpu" NVIDIA GPU limit for Fish Speech container
##
resources:
  limits:
    cpu: 1
    memory: 4Gi
    nvidia.com/gpu: 1
