## @param resources.limits.cpu CPU limit for Kubernetes resources
## @param resources.limits.memory Memory limit for Kubernetes resources
##
resources:
  limits:
    cpu: 1
    memory: 2Gi

## @param llm.provider Provider of the language model (`openai` or `ollama`)
## @param llm.apiKey API key for the language model provider
##
llm:
  # 使用的模型提供商
  # 应为 "openai" 或 "ollama"
  provider: ""
  apiKey: ""

  ## @param llm.openai.baseUrl Base URL for OpenAI API-compatible service
  ## @param llm.openai.fastModel Model name for fast LLM operations such summaries
  ## @param llm.openai.smartModel Model name for smart operations like generating research reports and reasoning
  ## @param llm.openai.fastTokenLimit Maximum token limit for fast LLM responses
  ## @param llm.openai.smartTokenLimit Maximum token limit for smart LLM responses
  ## @param llm.openai.summaryTokenLimit Maximum token limit for generating summaries
  ## @param llm.openai.temperature Sampling temperature for LLM responses, typically between 0 and 1. A higher value results in more randomness and creativity, while a lower value results in more focused and deterministic responses
  ##
  openai:
    # 兼容 OpenAI API 的服务的 URL
    # 如使用 OpenAI API，请设为 "https://api.openai.com/v1"
    baseUrl: ""
    fastModel: "gpt-3-turbo-16k"
    smartModel: "gpt-4-turbo"
    fastTokenLimit: "2000"
    smartTokenLimit: "4000"
    summaryTokenLimit: "700"
    temperature: "0.55"

  ## @param llm.ollama.baseUrl Base URL for Ollama API-compatible service
  ## @param llm.ollama.fastModel Model name for fast LLM operations such summaries
  ## @param llm.ollama.smartModel Model name for smart operations like generating research reports and reasoning
  ## @param llm.ollama.fastTokenLimit Maximum token limit for fast LLM responses
  ## @param llm.ollama.smartTokenLimit Maximum token limit for smart LLM responses
  ## @param llm.ollama.summaryTokenLimit Maximum token limit for generating summaries
  ## @param llm.ollama.temperature Sampling temperature for LLM responses, typically between 0 and 1. A higher value results in more randomness and creativity, while a lower value results in more focused and deterministic responses
  ##
  ollama:
    baseUrl: ""
    fastModel: "llama3"
    smartModel: "llama3"
    embeddingModel: "nomic-embed-text"
    fastTokenLimit: "2000"
    smartTokenLimit: "4000"
    summaryTokenLimit: "700"
    temperature: "0.55"

## @param retriever.provider Provider of the web search engine (`BingSearch`, `google`, `searx`, `serpapi`, `googleSerp`, or `tavily`)
## @param retriever.apiKey API key for the search engine provider
## @param retriever.google.cxKey CX key for Google search engine provider
##
retriever:
  # 使用的搜索引擎提供商
  # 应为 "BingSearch"、"google"、"searx"、"serpapi"、"googleSerp" 或 "tavily"
  provider: ""
  apiKey: ""
  google:
    cxKey: ""

## @param app.userAgent Custom User-Agent string for web crawling and web requests
## @param app.similarityThreshold Threshold for determining when two documents are similar enough to be considered redundant
## @param app.maxSearchResultsPerQuery Maximum search results per query
## @param app.memoryBackend Backend used for memory operations, such as local storage of temporary data
## @param app.totalWords Total word count limit for document generation or processing tasks
## @param app.reportFormat Preferred format for report generation (`APA`, `MLA`, `CMS`, `Harvard style`, or `IEEE`)
## @param app.maxIterations Maximum number of iterations for processes like query expansion or search refinement
## @param app.agentRole Role of the agent, this might be used to customize the behavior of the agent based on its assigned roles
## @param app.scraper Web scraper to use for gathering information
## @param app.maxSubtopics Maximum number of subtopics to generate or consider
##
app:
  # 应用的其他设置
  userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0"
  similarityThreshold: 0.38
  browseChunkMaxLength: 8192
  maxSearchResultsPerQuery: 5
  memoryBackend: local
  totalWords: 800
  reportFormat: APA
  maxIterations: 3
  agentRole: None
  scraper: "bs"
  maxSubtopics: 3

## @param env Array of extra environment variables
##
env: []
  # # HTTP 和 HTTPS 代理
  # - name: HTTP_PROXY
  #   value: ""
  # - name: HTTPS_PROXY
  #   value: ""
  # - name: NO_PROXY
  #   value: ".cluster.local"
