# +t9k:form:pattern v2

# +t9k:description:en Terminal image config.
# +t9k:description:zh Terminal 镜像信息。
image:
  # +t9k:form
  # +t9k:description:en Terminal image registry.
  # +t9k:description:zh Terminal 镜像仓库。 
  registry: "$(T9K_APP_IMAGE_REGISTRY)"
  # +t9k:form
  # +t9k:description:en Terminal image repository.
  # +t9k:description:zh Terminal 镜像名称。
  repository: "$(T9K_APP_IMAGE_NAMESPACE)/terminal"
  # +t9k:form
  # +t9k:description:en Terminal image tag.
  # +t9k:description:zh Terminal 镜像标签。
  tag: "240819"
  # +t9k:form
  # +t9k:description:en Terminal image pull policy.
  # +t9k:description:zh Terminal 镜像拉取策略。
  pullPolicy: IfNotPresent

# sh, bash or zsh
#
# +t9k:form
# +t9k:description:en Select a shell to start terminal.
# +t9k:description:zh 选择一个 Shell 启动 Terminal。
shell: bash

resources:
  # +t9k:description:en App resource limit.
  # +t9k:description:zh App 资源限额。
  limits:
    # +t9k:form
    # +t9k:description:en CPU limit for the App container.
    # +t9k:description:zh App CPU 限制。
    cpu: 200m
    # +t9k:form
    # +t9k:description:en Memory limit for the App container.
    # +t9k:description:zh App 内存限制。
    memory: 400Mi

# pvcs:
# - name: <pvc-1>
#   mountPath: /mnt/one
# - name: <pvc-2>
#   mountPath: /mnt/two
#
# +t9k:form
# +t9k:description:en Mount pvcs to terminal.
# +t9k:description:zh 挂载 pvcs 到 Terminal。
pvcs: []

global:
  t9k:
    homeURL: "$(T9K_HOME_URL)"
    securityService:
      enabled: true
      endpoints:
        oidc: "$(T9K_OIDC_ENDPOINT)"
        securityServer: "$(T9K_SECURITY_CONSOLE_SERVER_ENDPOINT)"
    pepProxy:
      image:
        registry: "$(T9K_APP_IMAGE_REGISTRY)"
        repository: "$(T9K_APP_IMAGE_NAMESPACE)/pep-proxy"
        tag: "1.0.14"
      args:
        clientID: $(T9K_APP_AUTH_CLINET_ID)
