apiVersion: tensorstack.dev/v1beta1
kind: Notebook
metadata:
  name: ""
spec:
  type: jupyter
  template:
    spec:
      containers:
        - name: notebook
          image: t9kpublic/torch-2.1.0-notebook:1.78.8
          volumeMounts:
            - name: workingdir
              mountPath: /t9k/mnt
          ## @param spec.template.spec.containers[0].resources.limits.cpu The maximum number of CPU the notebook can use.
          ## @param spec.template.spec.containers[0].resources.limits.memory The maximum number of CPU the notebook can use.
          resources:
            limits:
              cpu: "16"
              memory: 32Gi
              nvidia.com/gpu: 1
      volumes:
        - name: workingdir
          persistentVolumeClaim:
            ## @param spec.template.spec.volumes[0].persistentVolumeClaim.claimName Mount a pvc as notebook working directory.
            claimName: ""
