dependencies:
- name: etcd
  version: 6.3.3
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: etcd.enabled
  tags:
    - etcd
- name: minio
  version: 8.0.17
  repository: https://zilliztech.github.io/milvus-helm
  condition: minio.enabled
  tags:
    - minio
- name: pulsar
  alias: pulsarv3
  version: 3.3.0
  repository: https://pulsar.apache.org/charts
  condition: pulsarv3.enabled
  tags:
    - pulsarv3
- name: kafka
  version: 15.5.1
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: kafka.enabled
  tags:
    - kafka
