apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: web
    port: 2746
    targetPort: 2746
  selector:
    app: {{ .Release.Name }}
