apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "qdrant.fullname" . }}
  labels:
    {{- include "qdrant.labels" . | nindent 4 }}
spec:
  gateways:
  - project-gateway
  hosts:
  - '*'
  http:
  - headers:
      request:
        remove: 
        - cookie
    match:
    - uri:
        prefix: /t9k/app/qdrant/{{ .Release.Namespace }}/{{ .Release.Name }}/
    rewrite:
      uri: /
    route:
    - destination:
        host: {{ .Release.Name }}-qdrant
        port:
          {{- range .Values.service.ports }}
          {{- if eq .targetPort "6333" }}
          number: {{ .port }}
