apiVersion: tensorstack.dev/v1beta1
kind: Notebook
metadata:
  name: ""
spec:
  type: jupyter
  template:
    spec:
      containers:
        - name: notebook
          ## @param spec.template.spec.containers[0].image The image used for the notebook container.
          image: registry.cn-hangzhou.aliyuncs.com/t9k/torch-2.1.0-notebook:20240716
          volumeMounts:
            - name: workingdir
              mountPath: /t9k/mnt
          ## @param spec.template.spec.containers[0].resources.limits.cpu The maximum number of CPU the notebook can use.
          ## @param spec.template.spec.containers[0].resources.limits.memory The maximum number of CPU the notebook can use.
          resources:
            limits:
              cpu: "16"
              memory: 32Gi
      volumes:
        - name: workingdir
          persistentVolumeClaim:
            ## @param spec.template.spec.volumes[0].persistentVolumeClaim.claimName Mount a pvc as notebook working directory.
            claimName: ""
