apiVersion: tensorstack.dev/v1beta1
kind: SimpleMLService
metadata:
  name: {{ include "vllm.fullname" . }}
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  storage:
    pvc:
      {{- if .Values.model.volume.existingClaim }}
      name: {{ .Values.model.volume.existingClaim }}
      {{- else }}
      name: {{ include "vllm.fullname" . }}
      {{- end }}
      subPath: {{ .Values.model.volume.subPath }}
  service:
    type: ClusterIP
    ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  custom:
    spec:
      {{- if .Values.model.source }}
      initContainers:
        - name: wait-for-datacube
          image: bitnami/kubectl:1.27
          command: ["/bin/sh", "-c"]
          args: ["kubectl wait --for=condition=Complete datacube/{{ .Release.Name }} --timeout=-1s"]
      serviceAccount: managed-project-sa
      serviceAccountName: managed-project-sa
      {{- end }}
      containers:
      - name: server
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_PTRACE"]
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["python", "-m", "vllm.entrypoints.openai.api_server"]
        args:
          - --model=/var/lib/t9k/model
          - --served-model-name={{ .Values.model.deployName }}
          - --trust-remote-code
          - --tensor-parallel-size={{ (index .Values.resources.limits "hygon.com/dcu") }}
          - --enforce-eager
        {{- if eq (index .Values.resources.limits "hygon.com/dcu") 1 }}
        env:
        - name: HIP_VISIBLE_DEVICES
          value: "0"
        {{- else if eq (index .Values.resources.limits "hygon.com/dcu") 2 }}
        env:
        - name: HIP_VISIBLE_DEVICES
          value: "0,1"
        {{- else if eq (index .Values.resources.limits "hygon.com/dcu") 4 }}
        env:
        - name: HIP_VISIBLE_DEVICES
          value: "0,1,2,3"
        {{- end }}
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 60
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 60
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: hyhal
          mountPath: /opt/hyhal
          readOnly: true
        - name: dev-kfd
          mountPath: /dev/kfd
          readOnly: true
        - name: dev-dri
          mountPath: /dev/dri
          readOnly: true
        - name: dshm
          mountPath: /dev/shm
      volumes:
      - name: hyhal
        hostPath:
          path: /opt/hyhal
      - name: dev-kfd
        hostPath:
          path: /dev/kfd
      - name: dev-dri
        hostPath:
          path: /dev/dri
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: "80Gi"
