image:
  registry: registry.cn-hangzhou.aliyuncs.com
  repository: t9k/jupyterlab-torch-2.1.0
  tag: "240708-dcu"
  pullPolicy: IfNotPresent

pvc: ""

resources:
  limits:
    cpu: 16
    memory: 32Gi
    hygon.com/dcu: 1

ssh:
  enabled: false
  authorizedKeys: []
  serviceType: ClusterIP

nodeSelector: []
