## @param image.registry NextChat image registry
## @param image.repository NextChat image repository
## @param image.tag NextChat image tag
## @param image.pullPolicy NextChat image pull policy
##
image:
  registry: "$(T9K_APP_IMAGE_REGISTRY)"
  repository: "$(T9K_APP_IMAGE_NAMESPACE)/chatgpt-next-web"
  tag: "v2.15.8"
  pullPolicy: IfNotPresent

## @param resources.limits.cpu CPU limit for NextChat container
## @param resources.limits.memory Memory limit for NextChat container
##
resources:
  limits:
    cpu: 1
    memory: 2Gi

## @param llm.provider Provider of the language model (`openai`, `azure`, `anthropic`, or `google`)
## @param llm.apiKey API key for the language model provider
## @param llm.openai.baseUrl Base URL for OpenAI API-compatible servers
## @param llm.azure.url URL for Azure language model API
## @param llm.azure.apiVersion API version for Azure language model API
## @param llm.anthropic.url URL for Anthropic language model API
## @param llm.anthropic.apiVersion API version for Anthropic language model API
## @param llm.google.url URL for Google language model API
##
llm:
  # 使用的模型提供商
  # 应为 "openai"、"azure"、"anthropic"" 或 "google"
  provider: "openai"
  apiKey: ""
  openai:
    # 兼容 OpenAI API 的服务器的 URL
    # 如使用 OpenAI API，请设为 "https://api.openai.com"
    baseUrl: "https://api.openai.com"
    
  azure:
    url: ""
    apiVersion: ""

  anthropic:
    url: ""
    apiVersion: ""

  google:
    url: ""

## @param env Array of extra environment variables
##
env: []
  # - name: PROXY_URL
  #   value: ""
