apiVersion: tensorstack.dev/v1beta1
kind: MLServiceRuntime
metadata:
  name: {{ include "vllm.fullname" . }}
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
spec:
  enabled: true
  template:
    spec:
      {{- if .Values.datacube.source }}
      initContainers:
      - name: wait-for-datacube
        image: "{{ .Values.initializer.image.registry }}/{{ .Values.initializer.image.repository }}:{{ .Values.initializer.image.tag }}"
        imagePullPolicy: {{ .Values.initializer.image.pullPolicy }}
        command: ["/bin/sh", "-c"]
        args: ["kubectl wait --for=condition=Complete datacube/{{ include "vllm.fullname" . }} --timeout=-1s"]
        resources:
          {{- toYaml .Values.initializer.resources | nindent 10 }}
      {{- end }}
      serviceAccountName: managed-project-sa
      nodeSelector:
        {{- if .Values.server.nodeSelector }}
        {{- toYaml .Values.server.nodeSelector | nindent 8 }}
        {{- end }}
      containers:
      - name: user-container
        securityContext:
          {{- if .Values.server.securityContext }}
          {{- toYaml .Values.server.securityContext | nindent 10 }}
          {{- end }}
        image: "{{ .Values.server.image.registry }}/{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
        imagePullPolicy: {{ .Values.server.image.pullPolicy }}
        args:
          - --model=/var/lib/t9k/model
          - --served-model-name={{ .Values.server.model.deployName }}
          {{ range .Values.server.app.extraArgs }}
          - {{ . }}
          {{ end }}
        env:
          {{- if .Values.server.env }}
          {{- toYaml .Values.server.env | nindent 10 }}
          {{- end }}
        ports:
        - containerPort: 8000
          protocol: TCP
        resources:
          {{- toYaml .Values.server.resources | nindent 10 }}
        volumeMounts:
          - name: dshm
            mountPath: /dev/shm
          {{- if .Values.server.extraVolumeMounts }}
          {{- toYaml .Values.server.extraVolumeMounts | nindent 10 }}
          {{- end }}
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        {{- if .Values.server.extraVolume }}
        {{- toYaml .Values.server.extraVolume | nindent 8 }}
        {{- end }}
