## @param image.registry Repository registry for the Docker image
## @param image.repository Repository name for the Docker image
## @param image.tag Image tag for the Docker image (immutable tags are recommended)
## @param image.pullPolicy Image pull policy for the Docker image
##
image:
  registry: "$(T9K_APP_IMAGE_REGISTRY)"
  repository: "$(T9K_APP_IMAGE_NAMESPACE)/torch-2.1.0-notebook"
  tag: "20240716"
  pullPolicy: IfNotPresent

## @param pvc Mount a PVC as JupyterLab working directory
pvc: ""

## @param resources.limits.cpu CPU limit for the App container
## @param resources.limits.memory Memory limit for the App container
resources:
  limits:
    cpu: 16
    memory: 32Gi

## @param ssh.enabled Set true to start a SSH Service for JupyterLab
## @param ssh.authorizedKeys A list of names of v1.Secret containing SSH public keys authorized for access to this SSH service
## @param ssh.serviceType Type for the SSH service (`ClusterIP` or `NodePort`)
#
# ssh:
#   enabled: true
#   authorizedKeys:
#   - "secret-name"
#   serviceType: ClusterIP
#
ssh:
  enabled: false
  authorizedKeys: []
  serviceType: ClusterIP
