apiVersion: app.tensorstack.dev/v1beta1
kind: Template
metadata:
  name: jupyter-lab-cpu
  displayName: "Jupyter Lab (CPU)"
  categories: 
  - IDE
  description: "Jupyter Lab 是最新的基于 Web 的交互式开发环境，用于代码开发和数据处理。其灵活的界面允许用户配置和安排数据科学、科学计算、计算新闻和机器学习中的工作流程。"
  icon: "file://$APP_DIR/jupyter-lab-cpu/icon.svg"
template:
  crd:
    group: tensorstack.dev
    resource: notebooks
    versions:
    - version: v1beta1
      config: "file://$APP_DIR/jupyter-lab-cpu/config.yaml"
      readme: "file://$APP_DIR/jupyter-lab-cpu/README.md"
      note: "file://$APP_DIR/jupyter-lab-cpu/NOTE.txt"
      urls: 
      - name: "jupyter"
        url: "/t9k/notebooks/projects/{{ .metadata.namespace }}/name/{{ .metadata.name }}/lab"
      readinessProbe:
        resources:
        - group: tensorstack.dev
          version: v1beta1
          resource: notebooks
          name: "{{ .metadata.name }}"
          currentStatus: "{{- range .status.conditions }}{{- if eq .type \"Ready\" }}{{- .status }}{{- end }}{{- end }}"
          desiredStatus: "True"

---

apiVersion: app.tensorstack.dev/v1beta1
kind: Template
metadata:
  name: jupyter-lab-gpu
  displayName: "Jupyter Lab (Nvidia GPU)"
  categories: 
  - IDE
  description: "Jupyter Lab (Nvidia GPU) 是最新的基于 Web 的交互式开发环境，该 Jupyter Lab 配置了 Nvidia GPU，用户可以在其中进行 GPU 训练代码的开发。"
  icon: "file://$APP_DIR/jupyter-lab-gpu/icon.svg"
template:
  crd:
    group: tensorstack.dev
    resource: notebooks
    versions:
    - version: v1beta1
      config: "file://$APP_DIR/jupyter-lab-gpu/config.yaml"
      readme: "file://$APP_DIR/jupyter-lab-gpu/README.md"
      note: "file://$APP_DIR/jupyter-lab-gpu/NOTE.txt"
      urls: 
      - name: "jupyter"
        url: "/t9k/notebooks/projects/{{ .metadata.namespace }}/name/{{ .metadata.name }}/lab"
      readinessProbe:
        resources:
        - group: tensorstack.dev
          version: v1beta1
          resource: notebooks
          name: "{{ .metadata.name }}"
          currentStatus: "{{- range .status.conditions }}{{- if eq .type \"Ready\" }}{{- .status }}{{- end }}{{- end }}"
          desiredStatus: "True"

---

apiVersion: app.tensorstack.dev/v1beta1
kind: Template
metadata:
  name: rstudio
  displayName: RStudio
  categories: 
  - IDE
  description: "RStudio 集成开发环境 （IDE），旨在帮助你提高 R 和 Python 的工作效率。"
  icon: "file://$APP_DIR/rstudio/icon.svg"
template:
  crd:
    group: tensorstack.dev
    resource: notebooks
    versions:
    - version: v1beta1
      config: "file://$APP_DIR/rstudio/config.yaml"
      readme: "file://$APP_DIR/rstudio/README.md"
      note: "file://$APP_DIR/rstudio/NOTE.txt"
      urls: 
      - name: "rstudio"
        url: "/t9k/notebooks/projects/{{ .metadata.namespace }}/name/{{ .metadata.name }}/"
      readinessProbe:
        resources:
        - group: tensorstack.dev
          version: v1beta1
          resource: notebooks
          name: "{{ .metadata.name }}"
          currentStatus: "{{- range .status.conditions }}{{- if eq .type \"Ready\" }}{{- .status }}{{- end }}{{- end }}"
          desiredStatus: "True"
