image:
  registry: registry.cn-hangzhou.aliyuncs.com
  repository: t9k/terminal
  tag: "240611"
  pullPolicy: IfNotPresent

# sh, bash or zsh
shell: bash

pingIntervalSeconds: 30

resources:
  limits:
    cpu: 200m
    memory: 200Mi

# pvcs:
# - name: <pvc-1>
#   mountPath: /mnt/one
# - name: <pvc-2>
#   mountPath: /mnt/two
pvcs: []

global:
  t9k:
    homeURL: ""
    securityService:
      enabled: false
      endpoints:
        oidc: ""
        securityServer: ""
    pepProxy:
      image: "registry.cn-hangzhou.aliyuncs.com/t9k/pep-proxy:1.0.12"
      args:
        clientID: ""
