image:
  registry: docker.io
  repository: t9kpublic/terminal
  tag: "240716"
  pullPolicy: IfNotPresent

# sh, bash or zsh
shell: bash

pingIntervalSeconds: 30

resources:
  limits:
    cpu: 200m
    memory: 200Mi

# pvcs:
# - name: <pvc-1>
#   mountPath: /mnt/one
# - name: <pvc-2>
#   mountPath: /mnt/two
pvcs: []

global:
  t9k:
    homeURL: ""
    securityService:
      enabled: false
      endpoints:
        oidc: ""
        securityServer: ""
    pepProxy:
      image: "docker.io/t9kpublic/pep-proxy:1.0.10"
      args:
        clientID: ""
