apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "anythingllm.fullname" . }}
  labels:
    {{- include "anythingllm.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "anythingllm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "anythingllm.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: init-env
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["/bin/sh", "-c", "touch /app/server/.env"]
          volumeMounts:
            - name: storage
              mountPath: /app/server/
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 15
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 15
            failureThreshold: 5
          env:
            - name: STORAGE_DIR
              value: "/app/server/storage"
          volumeMounts:
            - name: storage
              mountPath: /app/server/storage
            - name: storage
              mountPath: /app/server/.env
              subPath: .env
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              add:
                - SYS_ADMIN
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ include "anythingllm.fullname" . }}
