apiVersion: app.tensorstack.dev/v1beta1
kind: Template
metadata:
  name: nextchat
  displayName: NextChat
  categories: ["AI"]
  description: "NextChat 是一个设计精良的 ChatGPT 网页 UI，支持 ChatGPT、Claude、Gemini 和本地部署的兼容 OpenAI API 的推理服务。"
  icon: "file://$APP_DIR/icon.png"
template:
  helm:
    repo: "oci://docker.io/t9kpublic"
    # repo: "https://t9k.github.io/apps/"
    chart: "nextchat"
    versions:
    - version: 0.1.3
      urls: 
      - name: UI
        url: /t9k/app/nextchat/{{ .Release.Namespace }}/{{ .Release.Name }}/
      readinessProbe:
        resources:
        - group: apps
          version: v1
          resource: deployments
          name: "{{ .Release.Name }}"
          currentStatus: "{{- range .status.conditions }}{{- if eq .type \"Available\" }}{{- .status }}{{- end }}{{- end }}"
          desiredStatus: "True"
      dependencies: {}
