## @param pvc Select a pvc as Code Server workspace.
pvc: ""

## @param resources.cpu The maximum number of CPU the Code Server can use.
## @param resources.memory The maximum number of memory the Code Server can use.
resources:
  cpu: 100m
  memory: 200Mi
