image:
  registry: docker.io
  repository: t9kpublic/jupyterlab-torch-2.5.0
  tag: "20241031"
  pullPolicy: IfNotPresent

volumes:
  workingDir: 
    pvc: ""
  extraVolumes: []

resources:
  limits:
    cpu: 16
    memory: 32Gi

ssh:
  enabled: false
  authorizedKeys: []
  serviceType: ClusterIP

nodeSelector: []
