image:
  registry: docker.io
  repository: t9kpublic/fastgpt
  tag: "v4.8.12"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 1
    memory: 2Gi

app:
  # 应用的设置，请参阅 https://github.com/labring/FastGPT/blob/main/files/docker/docker-compose-pgvector.yml#L94-L118
  defaultRootPassword: "123456"
  openAiBaseUrl: "http://app-one-api-xxx:3000/v1"
  chatApiKey: "sk-xxx"
  dbMaxLink: "30"
  tokenKey: "any"
  rootKey: "root_key"
  fileTokenKey: "filetoken"
  logLevel: "info"
  storeLogLevel: "warn"

  # 应用的配置文件，请参阅 https://doc.tryfastgpt.ai/docs/development/configuration/
  config:

    systemEnv:
      openapiPrefix: "fastgpt"
      vectorMaxProcess: 15
      qaMaxProcess: 15
      pgHNSWEfSearch: 100

    llmModels:
      - model: "gpt-3.5-turbo"
        name: "gpt-3.5-turbo"
        maxContext: 16000
        maxResponse: 4000
        quoteMaxToken: 13000
        maxTemperature: 1.2
        charsPointsPrice: 0
        censor: false
        vision: false
        datasetProcess: true
        usedInClassify: true
        usedInExtractFields: true
        usedInToolCall: true
        usedInQueryExtension: true
        toolChoice: true
        functionCall: false
        customCQPrompt: ""
        customExtractPrompt: ""
        defaultSystemChatPrompt: ""
        defaultConfig: {}
      # 其他 llm model 的配置 ...

    vectorModels:
      - model: "text-embedding-3-large"
        name: "Embedding-2"
        charsPointsPrice: 0
        defaultToken: 512
        maxToken: 3000
        weight: 100
        dbConfig: {}
        queryConfig: {}
        defaultConfig:
          dimensions: 1024
      # 其他 vector model 的配置 ...

    # reRankModels: []

    # audioSpeechModels: 
    #   - model: "tts-1"
    #     name: "OpenAI TTS1"
    #     charsPointsPrice: 0
    #     voices:
    #       - label: "Alloy"
    #         value: "alloy"
    #         bufferId: "openai-Alloy"
    #       # 其他 voices 的配置 ...
    #   # 其他 audio speech model 的配置

    # whisperModel:
    #   model: "whisper-1"
    #   name: "Whisper1"
    #   charsPointsPrice: 0
