apiVersion: app.tensorstack.dev/v1beta1
kind: Template
metadata:
  name: open-webui
  displayName: "Open WebUI"
  categories: ["AI"]
  description: "Open WebUI: A User-Friendly Web Interface for Chat Interactions 👋"
  icon: "file://$APP_DIR/icon.png"
template:
  helm:
    repo: "oci://docker.io/t9kpublic"
    chart: "open-webui"
    versions:
    - version: 2.1.0
      urls:
      - name: UI
        url: /t9k/app/open-webui/{{ .Release.Namespace }}/{{ .Release.Name }}/
      # readinessProbe:
      #   resources:
      #   - group: apps
      #     version: v1
      #     resource: deployments
      #     name: terminal-{{ .Release.Name }}
      #     currentStatus: "{{- range .status.conditions }}{{- if eq .type \"Available\" }}{{- .status }}{{- end }}{{- end }}"
      #     desiredStatus: "True"
      dependences: {}
