apiVersion: app.tensorstack.dev/v1beta1
kind: Template
metadata:
  name: open-webui
  displayName: "Open WebUI"
  categories: ["AI"]
  description: "Open WebUI: A User-Friendly Web Interface for Chat Interactions 👋"
  icon: "file://$APP_DIR/icon.png"
template:
  helm:
    repo: oci://registry.dockermirror.com/t9kpublic
    # repo: oci://registry.dockermirror.com/t9kpublic
    chart: "open-webui"
    versions:
    - version: 2.1.5
      config: "file://$APP_DIR/configs/v2_1.yaml"
      urls: []
      readinessProbe:
        resources:
        - group: apps
          version: v1
          resource: deployments
          name: "{{ .Release.Name }}"
          currentStatus: "{{- range .status.conditions }}{{- if eq .type \"Available\" }}{{- .status }}{{- end }}{{- end }}"
          desiredStatus: "True"
      dependencies: {}
