apiVersion: app.tensorstack.dev/v1beta1
kind: Template
metadata:
  name: open-webui
  displayName: "Open WebUI"
  categories: ["AI"]
  description: "Open WebUI 是一个用户友好的聊天交互网页界面。"
  icon: "file://$APP_DIR/icon.png"
template:
  helm:
    repo: "oci://docker.io/t9kpublic"
    # repo: "https://t9k.github.io/apps/"
    chart: "open-webui"
    versions:
    - version: 3.1.8
      config: "file://$APP_DIR/configs/v3_1_8.yaml"
      urls: []
      readinessProbe:
        resources:
        - group: apps
          version: v1
          resource: statefulsets
          name: "{{ .Release.Name }}"
          currentStatus: "{{- if ge .status.availableReplicas 1 }}True{{- else }}False{{- end }}"
          desiredStatus: "True"
        - group: apps
          version: v1
          resource: deployments
          name: "{{ .Release.Name }}-ollama"
          currentStatus: "{{- if ge .status.availableReplicas 1 }}True{{- else }}False{{- end }}"
          desiredStatus: "True"
        - group: apps
          version: v1
          resource: deployments
          name: "{{ .Release.Name }}-pipelines"
          currentStatus: "{{- if ge .status.availableReplicas 1 }}True{{- else }}False{{- end }}"
          desiredStatus: "True"
      dependencies: {}
