image:
  registry: docker.io
  repository: t9kpublic/comfyui
  tag: ""
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8188

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 4
    memory: 64Gi
    nvidia.com/gpu: 1

persistence:
  size: 64Gi
  storageClass: ""
  accessModes:
  - ReadWriteOnce
  existingClaim: ""

env: []
  # # HTTP 和 HTTPS 代理
  # - name: http_proxy
  #   value: ""
  # - name: https_proxy
  #   value: ""
