## @param resources.limits.cpu CPU limit for Kubernetes resources
## @param resources.limits.memory Memory limit for Kubernetes resources
##
resources:
  limits:
    cpu: 1
    memory: 2Gi

## @param image.registry Docker registry for the image
## @param image.repository Repository name for the image
## @param image.tag Tag for the image version
##
image:
  registry: "$(T9K_APP_IMAGE_REGISTRY)"
  repository: "$(T9K_APP_IMAGE_NAMESPACE)/search-with-lepton"
  tag: "20240730"


## @param llm.baseUrl URL of the server compatible with the OpenAI API
## @param llm.apiKey API key for accessing the OpenAI API
## @param llm.modelName Name of the model to be used, e.g., "gpt-3.5-turbo", "gpt-4-turbo", or "gpt-4o"
##
llm:
  # 兼容 OpenAI API 的服务器的 URL
  # 如使用 OpenAI API，请设为 "https://api.openai.com/v1"
  baseUrl: "https://api.openai.com/v1"
  apiKey: ""
  # 调用的模型名称，例如 "gpt-3.5-turbo"、"gpt-4-turbo" 或 "gpt-4o"
  modelName: ""

## @param searchEngine.provider Search engine provider to be used (`BING`, `GOOGLE`, `SERPER`, or `SEARCHAPI`)
## @param searchEngine.apiKey API key for accessing the search engine provider's API
## @param searchEngine.google.cxKey Custom search engine (Google) key
##
searchEngine:
  # 使用的搜索引擎提供商
  # 应为 "BING"、"GOOGLE"、"SERPER" 或 "SEARCHAPI"
  provider: ""
  apiKey: ""
  google:
    cxKey: ""

## @param env Array of extra environment variables
##
env: []
  # # HTTP 和 HTTPS 代理
  # - name: HTTP_PROXY
  #   value: ""
  # - name: HTTPS_PROXY
  #   value: ""
  # - name: NO_PROXY
  #   value: ".cluster.local"
