apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
  {{- if .Values.global.t9k.securityService.enabled }}
    targetPort: 4180
  {{- else }}
    targetPort: 8080
  {{- end }}
  selector:
    app: {{ .Release.Name }}
  type: ClusterIP