apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  gateways:
  - project-gateway
  hosts:
  - '*'
  http:
  - headers:
      request:
        add:
          x-auth-request-redirect: /apps/{{ .Release.Namespace }}/terminal/{{ .Release.Name }}/
    match:
    - uri:
        prefix: /apps/{{ .Release.Namespace }}/terminal/{{ .Release.Name }}/
    rewrite:
      uri: /
    route:
    - destination:
        host: {{ .Release.Name }}
        port:
          number: 8080
  {{- if not .Values.global.t9k.securityService.enabled }}
    headers:
      request:
        remove: 
        - cookie
  {{- end }}